// client-react/src/pages/Competitions.jsx
import DataTable from '../DataTable';
import { useFetchJson } from '../useFetchJson';

const COLUMNS = [
    { key: 'Sport', header: 'Sport' },
    { key: 'Competition_Name', header: 'Compétition' },
    { key: 'Competition_Track', header: 'Épreuve' },
    { key: 'Competition_Date', header: 'Date' },
    { key: 'Location_City', header: 'Ville' },
    { key: 'Location_Country', header: 'Pays' },
];

export default function Competitions() {
    const { data, error } = useFetchJson('/api/competitions');

    return (
        <div className="card">
            <h2>Liste des compétitions</h2>

            {error && <p>Erreur lors du chargement des compétitions.</p>}
            {!error && !data && <p className="loading">Chargement des compétitions...</p>}
            {!error && data && (
                <DataTable
                    columns={COLUMNS}
                    rows={data}
                    emptyMessage="Aucune compétition trouvée."
                />
            )}
        </div>
    );
}

// client-angular/src/app/pages/competitions.ts
import { Component } from '@angular/core';
import { DataTable, Column } from '../data-table/data-table';
import { useFetchJson } from '../use-fetch-json';

interface CompetitionRow {
    [key: string]: unknown;
    Sport: string;
    Competition_Name: string;
    Competition_Track: string;
    Competition_Date: string;
    Location_City: string;
    Location_Country: string;
}

const COLUMNS: Column[] = [
    { key: 'Sport', header: 'Sport' },
    { key: 'Competition_Name', header: 'Compétition' },
    { key: 'Competition_Track', header: 'Épreuve' },
    { key: 'Competition_Date', header: 'Date' },
    { key: 'Location_City', header: 'Ville' },
    { key: 'Location_Country', header: 'Pays' },
];

@Component({
    selector: 'app-competitions',
    imports: [DataTable],
    templateUrl: './competitions.html',
})
export class Competitions {
    columns = COLUMNS;
    protected readonly fetch = useFetchJson<CompetitionRow[]>('/api/competitions');
}
