// client-angular/src/app/pages/competitors.ts
import { Component } from '@angular/core';
import { DataTable, Column } from '../data-table/data-table';
import { useFetchJson } from '../use-fetch-json';

interface CompetitorRow {
    [key: string]: unknown;
    Last_Name: string;
    First_Name: string;
    Country_Residence: string;
}

const COLUMNS: Column[] = [
    { key: 'Last_Name', header: 'Nom' },
    { key: 'First_Name', header: 'Prénom' },
    { key: 'Country_Residence', header: 'Pays' },
];

@Component({
    selector: 'app-competitors',
    imports: [DataTable],
    templateUrl: './competitors.html',
})
export class Competitors {
    columns = COLUMNS;
    protected readonly fetch = useFetchJson<CompetitorRow[]>('/api/competitors');
}

// client-react/src/pages/Competitors.jsx
import DataTable from '../DataTable';
import { useFetchJson } from '../useFetchJson';

const COLUMNS = [
    { key: 'Last_Name', header: 'Nom' },
    { key: 'First_Name', header: 'Prénom' },
    { key: 'Country_Residence', header: 'Pays' },
];

export default function Competitors() {
    const { data, error } = useFetchJson('/api/competitors');

    return (
        <div className="card">
            <h2>Liste des compétiteurs</h2>

            {error && <p>Erreur lors du chargement des compétiteurs.</p>}
            {!error && !data && <p className="loading">Chargement des compétiteurs...</p>}
            {!error && data && (
                <DataTable
                    columns={COLUMNS}
                    rows={data}
                    emptyMessage="Aucun compétiteur trouvé."
                />
            )}
        </div>
    );
}
