// client-react/src/App.jsx
import { NavLink, Outlet } from 'react-router-dom';

// Site header/nav/footer shared across all pages, plus the routed page content.
export default function App() {
    return (
        <>
            <header>
                <h1>Compétitions Sportives</h1>

                <nav>
                    <NavLink to="/">Accueil</NavLink>
                    <NavLink to="/competitions">Compétitions</NavLink>
                    <NavLink to="/competitors">Compétiteurs</NavLink>
                    <NavLink to="/results">Résultats</NavLink>
                </nav>
            </header>

            <main>
                <Outlet />
            </main>

            <footer>Base de données sportive - Version 1.0</footer>
        </>
    );
}

// client-vue/src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router';
</script>

<template>
  <header>
    <h1>Compétitions Sportives</h1>

    <nav>
      <RouterLink to="/">Accueil</RouterLink>
      <RouterLink to="/competitions">Compétitions</RouterLink>
      <RouterLink to="/competitors">Compétiteurs</RouterLink>
      <RouterLink to="/results">Résultats</RouterLink>
    </nav>
  </header>

  <main>
    <RouterView />
  </main>

  <footer>Base de données sportive - Version 1.0</footer>
</template>
