// client-react/src/pages/Home.jsx
export default function Home() {
    return (
        <div className="card">
            <h2>Bienvenue</h2>

            <p>
                Cette application permet de consulter une base de données de
                compétitions sportives amateurs.
            </p>

            <p>Les sports actuellement gérés sont :</p>

            <ul>
                <li>Course à pied</li>
                <li>Cyclisme</li>
                <li>Natation</li>
            </ul>

            <p>
                Utilisez le menu de navigation pour consulter les compétitions,
                les compétiteurs et les résultats.
            </p>
        </div>
    );
}

// client-vue/src/pages/Home.vue
<template>
  <div class="card">
    <h2>Bienvenue</h2>

    <p>
      Cette application permet de consulter une base de données de
      compétitions sportives amateurs.
    </p>

    <p>Les sports actuellement gérés sont :</p>

    <ul>
      <li>Course à pied</li>
      <li>Cyclisme</li>
      <li>Natation</li>
    </ul>

    <p>
      Utilisez le menu de navigation pour consulter les compétitions,
      les compétiteurs et les résultats.
    </p>
  </div>
</template>
