// client-angular/src/app/use-fetch-json.ts
import { Signal, signal } from '@angular/core';
import { fetchJson } from './api';

// Shared data-fetching helper: loads JSON from the given API URL once, exposing the
// same loading/error/data signals each page needs.
export function useFetchJson<T>(url: string): { data: Signal<T | null>; error: Signal<Error | null> } {
    const data = signal<T | null>(null);
    const error = signal<Error | null>(null);

    fetchJson<T>(url)
        .then((result) => data.set(result))
        .catch((err: Error) => {
            console.error(err);
            error.set(err);
        });

    return { data, error };
}

// client-react/src/useFetchJson.js
import { useEffect, useState } from 'react';
import { fetchJson } from './api';

// Shared data-fetching hook: loads JSON from the given API URL once on mount,
// exposing the same loading/error/data states each page needs.
export function useFetchJson(url) {
    const [data, setData] = useState(null);
    const [error, setError] = useState(null);

    useEffect(() => {
        let cancelled = false;

        fetchJson(url)
            .then((result) => {
                if (!cancelled) setData(result);
            })
            .catch((err) => {
                console.error(err);
                if (!cancelled) setError(err);
            });

        return () => {
            cancelled = true;
        };
    }, [url]);

    return { data, error };
}
